---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Apply baseline role
      ansible.builtin.include_role:
        name: litpublic.rhel_system.baseline

    - name: Apply firewall role without service management
      ansible.builtin.include_role:
        name: litpublic.rhel_system.firewall
      vars:
        firewalld_manage_service: false
        services_enable: []
        ports_enable: []

    - name: Apply hardening role
      ansible.builtin.include_role:
        name: litpublic.rhel_system.hardening

    - name: Apply podman role with no package install
      ansible.builtin.include_role:
        name: litpublic.rhel_system.podman
      vars:
        packages: []
