---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: rhel-system-instance
    image: python:3.12-slim
    pre_build_image: true
    privileged: true
    command: /bin/sh -c "while true; do sleep 3600; done"

provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../../.."
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
