dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: rhel-system-instance
    image: python:3.12-slim
    pre_build_image: true
    privileged: true
    command: /bin/sh -c "while true; do sleep 3600; done"

provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: "${MOLECULE_PROJECT_DIRECTORY}/ansible.cfg"
    ANSIBLE_COLLECTIONS_PATH: >-
      /tmp/ansible_collections:${MOLECULE_PROJECT_DIRECTORY}/collections:/root/.ansible/collections:/usr/share/ansible/collections
    ANSIBLE_ROLES_PATH: >-
      ${MOLECULE_PROJECT_DIRECTORY}/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    side_effect: side_effect.yml
    cleanup: cleanup.yml

verifier:
  name: ansible
