---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure collection staging path exists
      ansible.builtin.file:
        path: /tmp/ansible_collections/ansible_collections/litpublic
        state: directory
        mode: "0755"

    - name: Link project collection into staging path
      ansible.builtin.file:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        dest: /tmp/ansible_collections/ansible_collections/litpublic/foundation_services
        state: link
        force: true
